name: dart_async
description: Módulo da Academia do Flutter de Dart Async
version: 1.0.0
homepage: https://academiadoflutter.com.br

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
