version: "3.1"
services:
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: dart_desafio_final
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mysql_data:/var/lib/mysql
