name: dart_fundamentos
description: projeto referente ao módulo de dart fundamentos da academia do flutter.
version: 1.0.0
# homepage: http://academiadoflutter.com.br

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
