name: dart_funcoes_colecoes
description: Módulo da Academia do Flutter de funções e coleções
version: 1.0.0
homepage: https://academiadoflutter.com.br

environment:
  sdk: ">=2.15.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
