name: dart_banco_dados
description: Módulo da Academia do Flutter de Dart Banco de Dados
version: 1.0.0
homepage: https://academiadoflutter.com.br

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  mysql1: ^0.19.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
